version: "3.9"

x-app: &default-app
  build:
    context: .
    args:
      - "RAILS_ENV=${RAILS_ENV:-development}"
  depends_on:
    - mysql
    - redis
  env_file:
    - ".env"
  volumes:
    - "./:/opt/app"

services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hotel_search_development
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=hs
      - MYSQL_PASSWORD=hs
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  api:
    <<: *default-app
    ports:
      - "8010:8010"

  worker:
    <<: *default-app
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    entrypoint: []

volumes:
  mysql: {}
  redis: {}