version: "3.9"

services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hotel_search
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=hs
      - MYSQL_PASSWORD=hstest
    ports:
      - '3306:3306'

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'

  hs:
    build:
      context: .
    volumes:
      - ./:/opt/app
    links:
      - mysql
      - redis
    ports:
      - '8010:8010'
    environment:
      - WORKER_PROCESSES=1
      - LISTEN_ON=0.0.0.0:8010
      - DATABASE_URL=mysql2://hs:hstest@mysql/hotel_search
      - CACHE_URL=redis://redis:6379/0
      - JOB_WORKER_URL=redis://redis:6379/0

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    links:
      - mysql
      - redis
    environment:
      - WORKER_PROCESSES=1
      - LISTEN_ON=0.0.0.0:8010
      - DATABASE_URL=mysql2://hs:hstest@mysql/hotel_search
      - CACHE_URL=redis://redis:6379/0
      - JOB_WORKER_URL=redis://redis:6379/0