apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
data:
  databaseUrl: "mysql2://hs:hs@prod-mysql/hotel_search_production"
  cacheUrl: "redis://prod-redis:6379/0"
  jobWorkerUrl: "redis://prod-redis:6379/0"