apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - job.yaml
images:
  - name: hs-app
    newName: hs-app
    newTag: v1
namePrefix: prod-