apiVersion: v1
kind: Service
metadata:
  labels:
    service: api
  name: api
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    service: api
  type: LoadBalancer
