apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-options
data:
  my.cnf: |-
    [mysqld]
    default-authentication-plugin=mysql_native_password
    log-bin-trust-function-creators=1
    sort_buffer_size=2621440
