apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: options
          configMap:
            name: mysql-options
      containers:
        - name: mysql
          image: "mysql:8"
          imagePullPolicy: "IfNotPresent"
          args: ["--max-connections=2048", "--performance-schema=OFF"]
          volumeMounts:
            - name: initialization
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              mountPath: /var/lib/mysql
            - name: options
              mountPath: /etc/mysql/conf.d
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-db
                  key: mysql-database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password
            - name: LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN
              value: "Y"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi