apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: worker
  strategy: {}
  template:
    metadata:
      labels:
        service: worker
    spec:
      containers:
        - name: worker
          image: 502479798840.dkr.ecr.us-east-2.amazonaws.com/hs-app:latest
          args:
            - bundle
            - exec
            - sidekiq
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: worker-env
                  key: databaseUrl
            - name: CACHE_URL
              valueFrom:
                configMapKeyRef:
                  name: worker-env
                  key: cacheUrl
            - name: JOB_WORKER_URL
              valueFrom:
                configMapKeyRef:
                  name: worker-env
                  key: jobWorkerUrl
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
