apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  labels:
    name: mysql-storage
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /data/mysql/