apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  labels:
    name: mysql-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: mysql-storage
  hostPath: /data/mysql/