extract_data_job_1:
  cron: "*/5 * * * *" # execute at every 5 minutes
  class: "ExtractDataJob"
  queue: default
  args:
    - "acme"

extract_data_job_2:
  cron: "*/5 * * * *"
  class: "ExtractDataJob"
  queue: default
  args:
    - "paperflies"

extract_data_job_3:
  cron: "*/5 * * * *"
  class: "ExtractDataJob"
  queue: default
  args:
    - "patagonia"