apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  destination:
    namespace: rails-app
    server: "https://kubernetes.default.svc"
  source:
    path: manifests
    repoURL: "https://github.com/duyeng/htsearch"
    targetRevision: circleci-project-setup
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false