apiVersion: v1
kind: ConfigMap
metadata:
  name: hs-api-config
  namespace: rails-app
data:
  worker-processes: "1"
  listen-on: "0.0.0.0:8010"
  database-url: "mysql2://hs:hs@mini-mysql/hotel_search_development"
  cache-url: "redis://redis:6379/0"
  job-worker-url: "redis://redis:6379/0"