apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - namespace.yaml
namespace: rails-app
images:
  - name: hs-app
    newName: hs-app
    newTag: v1